version: '3.8'

services:
  app:
    container_name: nest_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    env_file:
      - .env
    command: npm run start:prod
