name: pr CI

on:
  pull_request:
    branches:
      - '**' # 모든 브랜치에 PR 올릴 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show build number
        run: |
          echo "Build Number: ${{ github.run_number }}"

      - name: Show pull request number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Set Docker Image Tag
        id: set_docker_image_tag
        env:
          PR_NUMBER: ${{ steps.get_pr_number.outputs.PR_NUMBER }}
        run: |
          DOCKER_IMAGE_TAG="0.${{ github.event.pull_request.number }}.${{ github.run_number }}-pre-dev"
          echo "Docker Image Tag: $DOCKER_IMAGE_TAG"
          echo "DOCKER_IMAGE_TAG"="${DOCKER_IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/hiedu:$DOCKER_IMAGE_TAG .

      - name: Clone manifests repo
        run: |
          git clone https://github.com/inu-hiEDU/k8s-manifests.git

      # - name: Update deployment.yaml with new image
      #   run: |
      #     IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/hiedu:${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
      #     sed -i "s|image: .*/hiedu:.*|image: $IMAGE_NAME|" k8s-manifests/manifests/deployment.yaml

      - name: Commit and push image update
        run: |
          cd k8s-manifests
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/hiedu:${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
          sed -i "s|image: .*/hiedu:.*|image: $IMAGE_NAME|" manifests/deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add manifests/deployment.yaml
          git commit -m "chore: update image to ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/inu-hiEDU/k8s-manifests.git
